config/routes.rb
SampleApp::Application.routes.draw do
  resources :statusvalues

  resources :seasons
  resources :rates
  resources :users do
    resources :bookings
    member do
     get  'changepwd'
     post 'changepwdupd'
     put  'changepwdupd'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :addresses 
  resources :ustatuses
  resources :statusvalues


  root :to => 'pages#home'
  
  match '/signup',       to: 'users#new'
  match '/signin',       to: 'sessions#new'
  match '/signout',      to: 'sessions#destroy'

  match '/ap1',          :to => 'pages#ap1' 
  match '/ap2',          :to => 'pages#ap2'
  match '/ap3',          :to => 'pages#ap3'
  match '/ap9',          :to => 'pages#ap9'
  match '/apx',          :to => 'pages#apx'
  match '/booking_list', :to => 'pages#booking_list'
  match '/contact',      :to => 'pages#contact'
  match '/langude',      :to => 'pages#langude'
  match '/languen',      :to => 'pages#languen'
  match '/langufr',      :to => 'pages#langufr'
 

#'sessions#destroy' , via: :delete
  
end

app/models/season.rb
class Season < ActiveRecord::Base

attr_accessible :season, :langu, :text

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

before_filter :chk_admin

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seasons }
    end
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @season = Season.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/new
  # GET /seasons/new.json
  def new
    @season = Season.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/1/edit
  def edit
    @season = Season.find(params[:id])
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(params[:season])

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render json: @season, status: :created, location: @season }
      else
        format.html { render action: "new" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seasons/1
  # PUT /seasons/1.json
  def update
    @season = Season.find(params[:id])

    respond_to do |format|
      if @season.update_attributes(params[:season])
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url }
      format.json { head :no_content }
    end
  end

 private

  def chk_admin
    if is_admin?
    else
      redirect_to signin_path,  notice: "Please sign in as admin!"
    end
  end

end

app/helpers/seasons_helper.rb
module SeasonsHelper


end

app/views/seasons/_form.html.erb
<div class="row">
  <div class="span6 offset2">

<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br><br>
    <%= f.label :Season %>
    <%= f.number_field :season %>
<br>
    <%= f.label :Language %>
    <%= f.select :langu, [['English','EN'],['French','FR'],['German','DE']] %>
  <br>
    <%= f.label :text %>
    <%= f.text_field :text %>
 <br>
<br>
  <%= f.submit "Create Season", class: "btn btn-primary" %>
 
<% end %>
  </div>
</div>

app/views/seasons/edit.html.erb
<h2><strong>Editing season</h2></strong>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<h2><strong>Listing seasons</h2></strong>

<table>
  <tr>
    <th>Season</th>
    <th>Langu</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seasons.each do |season| %>
  <tr>
    <td><%= season.season %></td>
    <td><%= season.langu %></td>
    <td><%= season.text %></td>
    <td><%= link_to 'Show', season %></td>
    <td><%= link_to 'Edit', edit_season_path(season) %></td>
    <td><%= link_to 'Destroy', season, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h2><strong>New season</h2></strong>
<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Season:</b>
  <%= @season.season %>
</p>

<p>
  <b>Langu:</b>
  <%= @season.langu %>
</p>

<p>
  <b>Text:</b>
  <%= @season.text %>
</p>


<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>