config/routes.rb
SampleApp::Application.routes.draw do
  resources :statusvalues

  resources :seasons
  resources :rates
  resources :users do
    resources :bookings
    member do
     get  'changepwd'
     post 'changepwdupd'
     put  'changepwdupd'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :addresses 
  resources :ustatuses
  resources :statusvalues


  root :to => 'pages#home'
  
  match '/signup',       to: 'users#new'
  match '/signin',       to: 'sessions#new'
  match '/signout',      to: 'sessions#destroy'

  match '/ap1',          :to => 'pages#ap1' 
  match '/ap2',          :to => 'pages#ap2'
  match '/ap3',          :to => 'pages#ap3'
  match '/ap9',          :to => 'pages#ap9'
  match '/apx',          :to => 'pages#apx'
  match '/booking_list', :to => 'pages#booking_list'
  match '/contact',      :to => 'pages#contact'
  match '/langude',      :to => 'pages#langude'
  match '/languen',      :to => 'pages#languen'
  match '/langufr',      :to => 'pages#langufr'
 

#'sessions#destroy' , via: :delete
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_one :booking, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :ustatus
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

#  validates :name,  :presence => true,
#                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => true

# Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password
  before_update :encrypt_password
  before_save { |user| user.email = email.downcase }
#  before_save :create_remember_token

# Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

#    def create_remember_token
#      self.remember_token = SecureRandom.urlsafe_base64
#    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]

  def show
    correct_user
    @user = User.find(params[:id])
    @title = @user.name
    @address = Address.find_by_user_id(@user.id)
    @ustatus = Ustatus.where("user_id=?", @user.id)
    @booking = Booking.where(user_id: @user.id).last
 end

   def index
    admin_user
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
#      deactivate welcome e-mail; later use flag
#      UserMailer.welcome_email(@user).deliver
      redirect_to @user, :flash => { :success => "Your Account has been created!" }
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @address = Address.find_by_user_id(params[:id])
    if @address.present?
      @address.destroy
    end
    @ustatus = Ustatus.find_by_user_id(params[:id])
    if @ustatus.present?
      @ustatus.destroy
    end
    @Booking = Booking.find_by_user_id(params[:id])
    if @booking.present?
      @booking.destroy
    end
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def send_pdf
    send_file '/home/railsway/downloads/huge.zip', :type=>"application/zip" 
    redirect_to root_path
  end

  def changepwd
    correct_user
    @user = User.find(params[:id])
  end

  def changepwdupd
    @user = User.find(params[:id])
    user = User.authenticate(@user.email, params[:changepwd][:password])
    if user.nil?
      flash[:error] = "Password not correct"  
      render 'changepwd'
    else
 #     if params[:changepwd][:new_password] == params[:changepwd][:password_confirmation]
     @user.password = params[:changepwd][:new_password]
     @user.password_confirmation = params[:changepwd][:password_confirmation]  
     if @user.update_attributes(params[:user])
      flash[:success] = "password successfully changed"
      sign_in @user
      redirect_to @user
      else
        flash[:error] = "Passwords don't match or too small"  
        render 'changepwd'
      end
    end
    
  end



  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
#       redirect_to(signin_path) unless current_user?(@user)
       unless ( current_user?(@user) or is_admin? ) and signed_in?
         redirect_to(signin_path)
       end
    end

     def admin_user
      unless signed_in? and is_admin?  
        redirect_to signin_path, notice: "Please sign in as admin."
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper

def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

end

app/views/users/_form_message.html.erb
<div class="row">
  <div class="span4">
    <p>Any questions?</p>
    <%= form_for(:umessage, url: apx_path, method: "GET") do |f| %>
      <%= f.hidden_field :user_id, :value => @user.id %>
      <%= f.text_area :text %>
      <br>
      <%= f.submit "Send Message", confirm: 'Send Message?', class: "btn btn-info" %>
    <% end %>
  </div>
  <div class="span6">
    <br><br>
<% if langu == 'DE' %>
Bitte teilen Sie uns Ihre vollständige Adresse, sowie Festnetz- und Mobiltelefonnummer mit.
Wir werden Ihren persönlichen Bereich mit den entsprechenden Buchungsangaben aktualisieren.
Auf dem Kartenreiter "Booking History" können Sie sich über den Stand Ihrer Buchungsabwicklung informieren.
<br>
Falls Sie weitere Fragen haben, haben Sie die Möglichkeit uns eine Textmessage zu schicken, die wir umgehend
per e-Mail beantworten.
Sie können uns außerdem telefonisch unter +33 (0)4 93 65 70 28 erreichen. 
<% end %>
<% if langu == 'EN' %>
Please update your personal area with address, phone numbers (landline and mobile/cell phone) and your personal e-mail.
We will update your booking status accordingly. 
<br><br>
If you have further questions feel free to send us a text message which we will reply to as soon as possible. 
We could also be reached by phone +33 (0)4 93 65 70 28 or e-mail: studio@biot06.com
<% end %>
<% if langu == 'FR' %>
Merci de renseigner l'espace privée avec votre adresse, vos numéros de telephone fixe et portable, ainsi que votre adresse e-mail. Nous allons mettre à jour le status de votre réservation. Vous pouvez aussi télécharger le plan 
d'access.
<br><br>
Si vous avez d'autres questions n'hésitez pas de nous envoyer un message en utilisant la foncionalité de ce site.
Vous pouvez également nous contacter par e-mail:studio@biot06.com ou par telephone: 33 (0)4 93 65 70 28
  <% end %>
  </div>
</div> <!-- row -->

app/views/users/_tab_booking.html.erb
    <h3>Your booking Details:</h3>
    <br>  
    <% if @booking.nil? %>
      <p>No Booking Details Available</p>
      <br><br><br>
    <% else %>
       <div class="row">
         <div class="span2">
           <p><strong>Arrival:</strong></p>
         </div>
         <div class="span2">
           <p><%= @booking.adate %> </p> 
         </div>
         <div class="span2">
           <p><strong>Departure:</strong></p>
         </div>
         <div class="span2">
           <p><%= @booking.ddate %> </p>
         </div>
       </div> <!--row -->

       <div class="row">
         <div class="span2">
           <p><strong>No. Nights:</strong></p>
         </div>
         <div class="span2">
           <p><%= @booking.nights %> </p> 
         </div>
         <div class="span2">
           <p><strong>No. People:</strong></p>
         </div>
         <div class="span2">
           <p><%= @booking.people %> </p>
         </div>
       </div> <!--row -->

       <div class="row">
         <div class="span2">
           <p><strong>Total Price:</strong></p>
         </div>
         <div class="span2">
           <p><%= @booking.price %> </p> 
         </div>
         <div class="span2">
           <p><strong>Downpayment:</strong></p>
         </div>
         <div class="span2">
           <p><%= @booking.downp %> </p>
         </div>
       </div> <!--row -->

       <div class="row">
         <div class="span2">
           <p><strong>Final Cleaning:</strong></p>
         </div>
         <div class="span2">
           <p><%= @booking.cleaning %> </p> 
         </div>
       </div> <!--row -->

    <% end %>

    <% if is_admin? %>
       <%= link_to "New Booking", new_user_booking_path(@user) , class: "btn btn btn-info" %>
       <%= link_to "Change Booking", edit_user_booking_path(@user) , class: "btn btn btn-info" %>       
    <% end %>
    <%= link_to "All Bookings", user_bookings_path(@user) , class: "btn btn btn-info" %> 

app/views/users/_tab_findus.html.erb
<br> 
<% if langu == 'EN' %>
      <h3>Address</h3>
      <br>
       Matthias Scheele<br>
       7, Place Marius Auzias<br>
       06410 Biot <br>
      Tel: +33 (0)43 93 65 70 28<br>
      <br><strong>
      <%= link_to "Download Biot Map", '/plan_access.pdf' %>
      </strong><br><br>

      <strong>By Car:</strong> On the A8 motorway (Autoroute du Soleil) please take exit no 44 
      “Antibes/Juan Les Pins”. Coming from Nice just follow the signs indicating Biot. Coming from 
      Cannes, take direction “Antibes” at the first roundabout and at the second follow direction 
      “Marineland”/Biot. We would like to emphasise again that you cannot drive all the way to the 
      apartment and that there is no parking space within the old village. After having contacted 
      us it is possible though to access the village and to unload your car. Afterwards you park 
      the car on one of the public parking lots located at the village entrances, preferably 
      “Parking St. Jean” or “Parking de la Fontanette”. A few minutes walk up the hill and you are 
      back in the village.
      <hr>
      <strong>By train:</strong> You can either get off the train at “Gare de Biot” or “Gare d’Antibes”. 
      From both stations there is a bus which serves “Biot Village”.
      <hr>
      <strong>By Plane:</strong> You arrive at Nice Airport. If you plan to hire a car you can do this 
      easily at both Terminal 1 and 2. From the airport please follow the signs to the A8 motorway 
      (direction Antibes/Cannes). For further information refer to the above paragraph “How to find us 
      by car”. If you choose to stay without a car you can take the airport bus from Terminal 1 to 
      “Gare de Biot” for 1,30 Euro per person. If you arrive at Terminal 2 a shuttle bus (Navette) gets 
      you to Terminal 1. Of course you can take a cab but in the south of France this is quite expensive 
      (approx. 70 Euros for a ride to Biot). 
<% end %>
<% if langu == 'DE' %>
      <h3>Adresse</h3>
      <br>
       Matthias Scheele<br>
       7, Place Marius Auzias<br>
       06410 Biot <br>
      Tel: +33 (0)43 93 65 70 28<br>
      <br><strong>
      <%= link_to "Lageplan Biot", '/plan_access.pdf' %>
      </strong><br><br>

      <strong>Mit dem Auto</strong> erreichen Sie Biot über die Küstenautobahn A8. 
      Verlassen Sie die Autobahn an der Ausfahrt
      Nummer 44 "Antibes". Von dort aus folgen Sie der Beschilderung in Richtung Biot. Nach ca. 7 km erreichen 
      Sie das Dorf Biot.
      
      Wir möchten Sie noch einmal darauf hinweisen, dass die Ferienwohnung nicht direkt mit dem Auto zu erreichen
      ist, da es im Dorfkern keine Parkmöglichkeiten gibt. Zum Be- und Entladen des Gepäcks kann man aber nach
      Rücksprache mit uns ins Zentrum fahren und den Wagen dort für eine kurze Zeit abstellen. Anschließend parkt 
      man den Wagen auf einem der anliegenden öffentlichen Parkplätze, die sich unmittelbar in der Nähe des Dorfkerns
      befinden und innerhalb von zwei bis drei Minuten zu Fuß zu erreichen sind; es geht allerdings ein bisschen     
      bergauf. Am Besten stellen Sie Ihr Fahrzeug auf dem "Parking de la Fontanette" oder dem "Parking St. Jean" ab.
      <hr>
      <strong>Mit der Bahn</strong> fahren Sie bis zum Gare Biot oder Gare Antibes. 
      Von beiden Bahnhöfen fährt ein Bus bis nach 
      „Biot Village“.
      <hr>
      <strong>Mit dem Flugzeug</strong> landen Sie am Flughafen Nizza (Nice Aeroport). 
      Wenn Sie sich ein Auto mieten wollen, 
      so ist dies bequem am Terminal 1 und 2 möglich. Vom Flughafen folgen Sie der Beschilderung zur Autobahn 
      (s.o.). Möchten Sie ohne Auto bleiben, können Sie einen Flughafenbus vom Terminal 1 nehmen. Dieser fährt 
      Sie bis zum Bahnhof Biot. Sollten Sie am Terminal 2 ankommen, dann fährt Sie der kostenlose 
      Transferbus/Navette bis zum Busbahnhof am Terminal 1. Sie können natürlich auch in ein Taxi steigen, aber
      Taxifahren ist in Südfrankreich relativ teuer. Für die ca. halbstündige Fahrt vom Flughafen bis Biot muss 
      mit einem Fahrpreis von ca. 70 Euro gerechnet werden.
<% end %>
<% if langu == 'FR' %>
      <h3>Adresse</h3>
      <br>
       Matthias Scheele<br>
       7, Place Marius Auzias<br>
       06410 Biot <br>
      Tel: +33 (0)43 93 65 70 28<br>
      <br><strong>
      <%= link_to "Télécharger plan Biot village", '/plan_access.pdf' %>
      </strong><br><br>

     En Voiture: Suivez l'autoroute A8 et prenez la sortie numéro 44 'Antibes'. Suivez les indications 'Biot'. 
     Après environ 7 km, vous arrivez au pied du vieux village. Comme déjà indiqué avant, il n'y a pas de
     possibilié de se garer devant l'appartement car l'accès du village en voitures est limité. Pour charger 
     et décharger la voiture vous pourrez cependant entrer dans le village et stationner un moment. Ensuite vous
     pourrez garer votre voiture sur un des parkings publics qui se trouvent directement au pied du village. Pour
     rejoindre la maison depuis le 'parking de la Fontanette' ou du 'parking St. Jean' il faut compter environ 
     trois minutes. 
<% end %>

app/views/users/_tab_history.html.erb
    <h3>Your Booking History:</h3>
    <br>  
    <% if @ustatus.nil? %>
         <p>No status available</p>
         <br><br><br>
    <% else %>
      <% @ustatus.each do |ustatus|  %>
        <div class="row">
          <div class="span2">
            <p><%= ustatus.sdate %> </p> 
          </div>
          <div class="span4">
            <p><%= status_text(ustatus) %> </p> 
          </div>
        
        <% if is_admin? %>
        <%= link_to 'Delete', ustatus, confirm: 'Are you sure?', method: :delete %>
        <% end %>
        </div>
      <% end %>
    <% end %>
      <% if is_admin? %>
        <%= link_to "Add Status", edit_ustatus_path , class: "btn btn btn-info" %>
      <% end %>

app/views/users/_tab_person.html.erb
    <% if @address.nil? %>
           <p>your address is not maintained, please maintain address here</p>
           <br><br><br>
           <%= link_to "Create Address", edit_address_path , class: "btn btn btn-info" %>
    <% else %>
         <h3>Your Personal Data:</h3>
         <br>

         <div class="row"> 

           <div class="span2">
             <p><strong>First Name:</strong></p>
           </div>
           <div class="span2">
             <p><%= @address.fname %> </p> 
           </div>
           <div class="span2">
             <p><strong>Last Name:</strong></p>
           </div>
           <div class="span2">
             <p><%= @address.lname %> </p>
           </div>
         </div> <!--row -->
         
         <div class="row">
           <div class="span2">
             <p><strong>Street:</strong></p>
           </div>
           <div class="span2">
             <p><%= @address.streetno %> </p> 
           </div>
           <div class="span2">
             <p><strong>Phone</strong></p>
           </div>
           <div class="span3">
             <p><%= @address.phone1 %> </p>
           </div>
         </div>   <!--row -->

         <div class="row">
           <div class="span2">
             <p><strong>City:</strong></p>
           </div>
           <div class="span2">
             <p><%= @address.city %> </p> 
           </div>
           <div class="span2">
             <p><strong>Mobile</strong> </p>
           </div>
           <div class="span3">
             <p><%= @address.phonem %> </p>
           </div>
         </div> <!--row -->


         <div class="row">
           <div class="span2">
             <p><strong>Zip:</strong></p>
           </div>
           <div class="span2">
             <p><%= @address.zip %> </p> 
           </div>
           <div class="span2">
             <p><strong>Country:</strong></p>
           </div>
           <div class="span2">
             <p><%= @address.country %> </p> 
           </div> 
         </div> <!--row -->

       <div class="row">
         <div class="span4 ">
           <br>
           <%= link_to "Change Address", edit_address_path , class: "btn btn btn-info" %>
           <%= link_to "Change Password", changepwd_user_path , class: "btn btn btn-info" %>
         </div>
       </div> <!--row -->
    <% end %>
         

app/views/users/changepwd.html.erb
<%= provide(:title, 'Change your Password') %>
<br>
<h2><strong>Change Password for 
<%= @user.name %>
</h2></strong>
<br>
<br>
<div class="row" align="center">
  <div id="containerform">   
    <%= form_for(:changepwd, :url => { :action => "changepwdupd" })  do |f| %>
                
          <% flash.each do |key, value| %>
            <div class="alert alert-error">
              <%= content_tag(:div, value, :class => "flash #{key}") %>
            </div>
          <% end %>


      <%= f.label :password, "Old Password" %>
      <%= f.password_field :password %>
<br>
      <%= f.label :new_password, "New Password" %>
      <%= f.password_field :new_password %>
<br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
<br>

      <%= f.submit "Save Changes", class: "btn  btn-info" %>
      <%= link_to 'Back', @user %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h2><strong>Update your profile</h2></strong>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>

<h2><strong>Users</h2></strong>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
      <%= link_to "Delete", user, method: :delete, data:{ confirm: "Are you sure?"}  %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up New User') %>
<br>
<h2><strong>Sign up User</h2></strong>
<br>
<br>
<div class="row" align="center">
  <div id="containerform">    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>
<br>
      <%= f.label :email %>
      <%= f.text_field :email %>
<br>
      <%= f.label :password %>
      <%= f.password_field :password %>
<br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
<br>
<br>
      <%= f.submit "Create User", class: "btn  btn-info" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="span10">
    <ul class="media-grid">      
      <li><a><img src="/assets/intro_biot_long2.jpg"></a></li> 
    </ul>
  </div>
</div>


<% provide(:title, @user.name) %>
    <section>
        <p><big><strong>
          <% flash.each do |key, value| %>
          <br>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
          <% end %>
        <p></big></strong> 
      <h2><strong>
        Hello 
        <%= @user.name %>
      </h2></strong>
      <br>
      <br>

    <ul class="nav nav-tabs" id="FMStab">
    <li class="active"><a href="#person">Personal Data</a></li>
    <li><a href="#booking">Your Booking</a></li>
    <li><a href="#history">Booking History</a></li>
    <% if check_status? %>
    <li><a href="#findus">Directions</a></li>
    <% end %>
    </ul>


<div class="tab-content">


<div class="tab-pane active" id="person">
  <br>
  <div class="fms2">
   <%= render 'tab_person' %>
  </div> <!--fms2 frame -->
</div> <!-- tab -->

<div class="tab-pane" id="booking">
  <br>
  <div class="fms2">
   <%= render 'tab_booking' %>
  </div> <!-- frame -->
</div> <!-- tab -->

<div class="tab-pane" id="history">
  <br>
  <div class="fms2">
   <%= render 'tab_history' %>
  </div>  <!-- fms2 frame -->  
</div> <!-- tab -->

  <% if check_status? %>
    <div class="tab-pane" id="findus">
      <br>
      <div class="fms2">
        <%= render 'tab_findus' %>
      </div>  <!-- fms2 frame -->  
    </div> <!-- tab findus -->
  <% end %>



    <script>
    
    $('#FMStab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    })
    </script>

     <br><br>

     

<!-- Message form --> 

<%= render 'form_message' %>

   
    </div>


        
    </section>
       