config/routes.rb
SampleApp::Application.routes.draw do
  resources :statusvalues

  resources :seasons
  resources :rates
  resources :users do
    resources :bookings
    member do
     get  'changepwd'
     post 'changepwdupd'
     put  'changepwdupd'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :addresses 
  resources :ustatuses
  resources :statusvalues


  root :to => 'pages#home'
  
  match '/signup',       to: 'users#new'
  match '/signin',       to: 'sessions#new'
  match '/signout',      to: 'sessions#destroy'

  match '/ap1',          :to => 'pages#ap1' 
  match '/ap2',          :to => 'pages#ap2'
  match '/ap3',          :to => 'pages#ap3'
  match '/ap9',          :to => 'pages#ap9'
  match '/apx',          :to => 'pages#apx'
  match '/booking_list', :to => 'pages#booking_list'
  match '/contact',      :to => 'pages#contact'
  match '/langude',      :to => 'pages#langude'
  match '/languen',      :to => 'pages#languen'
  match '/langufr',      :to => 'pages#langufr'
 

#'sessions#destroy' , via: :delete
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
attr_accessible :apartment, :season, :price

end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

  before_filter :chk_admin

  # GET /rates
  # GET /rates.json
  def index
    @seasons = Season.all
    @rates = Rate.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.json
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render json: @rate, status: :created, location: @rate }
      else
        format.html { render action: "new" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :no_content }
    end
  end

  private

  def chk_admin
    if is_admin?
    else
       redirect_to signin_path,  notice: "Please sign in as admin!"
    end
  end

end

app/helpers/rates_helper.rb
module RatesHelper

def season(type)

# english only
      if type == 1
        @seasons = Season.where("season = 1")
      end
      if type == 2
        @seasons = Season.where("season = 2")
      end
      if type == 3
        @seasons = Season.where("season = 3")
      end
      if type == 4
        @seasons = Season.where("season = 4")
      end
      if type == 9
        @seasons = Season.where("langu = EN")
      end

end

end

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br><br>
    <%= f.label :apartment %>
    <%= f.number_field :apartment %>
<br>
    <%= f.label :season %>
    <%= f.number_field :season %>
  <br>
    <%= f.label :price %>
    <%= f.number_field :price %>
  <br><br>
      <%= f.submit "Create/Change Rate", class: "btn btn-primary" %>
  
<% end %>

app/views/rates/edit.html.erb
<h2><strong>Edit rate for season  </h2></strong>

<div class="row">
  <div class="span6 offset2">
<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

</div>
</div>

app/views/rates/index.html.erb
        <h2><strong>Maintain rates for all apartments</h2></strong>
        <br />
        <h3> apartment=1 Studio Nid de l'Airette</h3>
        <br />

        <p> Season indicators in English </p>
        <% @seasons.each do |season|  %>
          <%=  season.season %>
          <%=  season.text %>
          <br>
        <% end %>
        <br><hr>
        <table>
          <tr>
            <th>Apartment</th>
            <th>Season</th>
            <th>Price</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

          <% @rates.each do |rate| %>
            <tr>
              <td><%= rate.apartment %></td>
              <td><%= rate.season %></td>
              <td><%= rate.price %></td>
              <td><%= link_to 'Show', rate %></td>
              <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
              <td><%= link_to 'Destroy', rate, confirm: 'Are you sure?', method: :delete %></td>
            </tr>
         <% end %>
        </table>

    <br />

    <%= link_to 'New Rate', new_rate_path %>
 

app/views/rates/new.html.erb
<h2><strong>New rate</h2></strong>
<div class="row">
  <div class="span6 offset2">
    <%= render 'form' %>
    <%= link_to 'Back', rates_path %>
  </div>
</div>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Apartment:</b>
  <%= @rate.apartment %>
</p>

<p>
  <b>Season:</b>
  <%= @rate.season %>
</p>

<p>
  <b>Price:</b>
  <%= @rate.price %>
</p>


<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>