config/routes.rb
SampleApp::Application.routes.draw do
  resources :statusvalues

  resources :seasons
  resources :rates
  resources :users do
    resources :bookings
    member do
     get  'changepwd'
     post 'changepwdupd'
     put  'changepwdupd'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :addresses 
  resources :ustatuses
  resources :statusvalues


  root :to => 'pages#home'
  
  match '/signup',       to: 'users#new'
  match '/signin',       to: 'sessions#new'
  match '/signout',      to: 'sessions#destroy'

  match '/ap1',          :to => 'pages#ap1' 
  match '/ap2',          :to => 'pages#ap2'
  match '/ap3',          :to => 'pages#ap3'
  match '/ap9',          :to => 'pages#ap9'
  match '/apx',          :to => 'pages#apx'
  match '/booking_list', :to => 'pages#booking_list'
  match '/contact',      :to => 'pages#contact'
  match '/langude',      :to => 'pages#langude'
  match '/languen',      :to => 'pages#languen'
  match '/langufr',      :to => 'pages#langufr'
 

#'sessions#destroy' , via: :delete
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="container">
Contact us for more information by <strong>phone: +33 (0)4 93 65 70 28</strong> 
or by 
<strong>mail:  studio@biot06.com</strong>

<ul class="nav pull-right">
FMS Site 2012
</ul>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
        <li><%= link_to "DE", langude_path %></li>
        <li><%= link_to "EN", languen_path %></li>
        <li><%= link_to "FR", langufr_path %></li>
        </ul> 
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path, id: "logo" %></li>
          <li><%= link_to "Apartment", ap1_path %></li>
          <li><%= link_to "Biot Info", ap2_path %></li>
          <li><%= link_to "Biot Activities", ap3_path %></li>
          <% if signed_in? %>
            <% if is_admin? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Customising <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Maintain rates", rates_path %></li>
                  <li><%= link_to "Maintain seasons", seasons_path %></li>
                  <li><%= link_to "Maintain User Status Values", statusvalues_path %></li>
                </ul>
              </li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  User Management <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "List all bookings", booking_list_path %></li>
                  <li><%= link_to "Show user", users_path %></li>
                  <li><%= link_to "Sign Up User", signup_path %></li>                
                </ul>
              </li>
            <% end %>
            <% if is_group1? %>
              <li><%= link_to "List all bookings", booking_list_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_lastrow.html.erb
<!--Last row on every page-->
<div class="fmslrow">
  <div class="row">    
More about Biot, the surroundings and activities....
</div>      
<br>
  <div class="row">    
    <h3>
    <div class="span2 offset1">
      <%= link_to "Biot Community","http://www.biot.fr", :target => "_blank" %>
    </div>
    <div class="span2">
      <%= link_to "verrerie de Biot","http://www.verreriebiot.com", :target => "_blank" %>
    </div>
    <div class="span2">
      <%= link_to "Fernand Leger","http://www.musees-nationaux-alpesmaritimes.fr/fleger/", :target => "_blank" %>
    </div>
    <div class="span2">
      <%= link_to "Marineland","http://www.marineland.fr", :target => "_blank"%>
    </div>
    </h3>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= stylesheet_link_tag    "application", media:"all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>

  <body>

    <div class="container">
      <%= render 'layouts/header' %>
      <div class="boxhead"></div>
      <section class="round">
      <div class="hero-unit">
          <%= yield %>
      </div>
      </section>
    </div>
      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    
  </body>
</html>